// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdgaweexijfkpjfyolyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkZ2F3ZWV4aWpma3BqZnlvbHlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NjcxOTgsImV4cCI6MjA2MDE0MzE5OH0.JafaoUP7wx62w38wC4htMCZl55uZE-WEpeMyfDLmUrc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);